build: t_client fixups
Configuratioan file should be consistent either in srcdir or builddir.

Produce one line per SKIP error.

Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

diff --git a/tests/t_client.sh.in b/tests/t_client.sh.in
--- a/tests/t_client.sh.in
+++ b/tests/t_client.sh.in
@@ -13,14 +13,14 @@
 #
 
 srcdir="${srcdir:-.}"
+builddir="${builddir:-${srcdir}}"
 top_builddir="${top_builddir:-..}"
-if [ -r "${top_builddir}"/t_client.rc ] ; then
-    . "${top_builddir}"/t_client.rc
+if [ -r "${builddir}"/t_client.rc ] ; then
+    . "${builddir}"/t_client.rc
 elif [ -r "${srcdir}"/t_client.rc ] ; then
     . "${srcdir}"/t_client.rc
 else
-    echo "$0: cannot find 't_client.rc' in build dir ('${top_builddir}')" >&2
-    echo "$0: or source directory ('${srcdir}'). SKIPPING TEST." >&2
+    echo "$0: cannot find 't_client.rc' in ('${srcdir}', '${builddir}'). SKIPPING TEST." >&2
     exit 77
 fi
 
